# This configuration builds the repository and runs benchmarks

# Don't run CI for this config
trigger: none

pr:
- '*'

variables:
- template: /eng/common/templates/variables/pool-providers.yml

jobs:
- template: jobs/default-build.yml
  parameters:
    jobName: Windows_Build
    jobDisplayName: "Build: Windows"
    agentOs: Windows
    buildArgs: -all -pack
    artifacts:
    - path: artifacts/
      includeForks: true
